Repository dod-advana/gamechanger-web, pull requests merged in 2021-11, with the labels that each got.

#261 print crawler name if crawler name does not match pg table
  frontend/src/components/dataTracker/GCDataStatusTracker.js
Labels: v1.5

#256 Added jaic logo to footers.
  frontend/src/App.js
  frontend/src/components/navigation/GCFooter.js
Labels: v1.5

#262 fix widths of favorite cards
  frontend/src/components/cards/GCFavoriteCard.js
  frontend/src/components/cards/GCGroupCard.js
  frontend/src/components/cards/GCGroupFavoriteCard.js
  frontend/src/components/user/GCUserDashboard.js
  frontend/src/containers/gamechanger.css
Labels: v1.5

#263 Fix favoriting docs on source details page
  frontend/src/components/details/sourceDetailsPage.js
  frontend/src/containers/GameChangerDetailsPage.js
Labels: v1.5

#269 bugfix/UOT-118768: Recommended titles should show up first in search results
  backend/node_app/utils/searchUtility.js
  backend/test/modules/policy/policyGraphHandler.test.js
  backend/test/utils/searchUtility.test.js
Labels: v1.6

#268 UOT-118767: Adding finetuning/evals to ML Dashboard
  frontend/src/components/admin/MLDashboard/models.js
Labels: v1.6

#208 Bugfix/uot 110228
  frontend/src/App.js
Labels: v1.6

#274 Hotfix/title search error
  backend/node_app/controllers/textSuggestionController.js
  backend/node_app/utils/searchUtility.js
  backend/test/modules/policy/policyGraphHandler.test.js
  backend/test/utils/searchUtility.test.js
Labels: v1.6

#275 UOT-121280 add tags and custom properties to search
  backend/node_app/modules/globalSearch/globalSearchHandler.js
Labels: v1.6

#281 Task/UOT-117943 - Pagination Fixes
  backend/node_app/controllers/dataTrackerController.js
  frontend/src/components/dataTracker/GCDataStatusTracker.js
  frontend/src/containers/GameChangerDetailsPage.js
Labels: v1.7

#280 Task/UOT-108861 - Graph View Fixes
  frontend/src/components/graph/GraphNodeCluster2D.js
  frontend/src/components/graph/policyGraphView.js
Labels: v1.7
