Repository dod-advana/gamechanger-web, pull requests merged in 2022-05, with the labels that each got.

#508 fixed most recent pdfs not showing
  backend/node_app/controllers/appStatsController.js
Labels: bugfix, v1.14

#499 removing OPM from code + tests.
  backend/node_app/utils/routeUtility.js
  backend/test/resources/mockResponses/qaESReturn.js
  backend/test/utils/searchUtility.test.js
  frontend/src/utils/gamechangerUtils.js
Labels: bugfix, v1.14

#497 using an npm package to handle all plural cases
  frontend/package.json
  frontend/src/components/analystTools/GCDocumentsComparisonTool.js
  frontend/src/components/modules/policy/policySearchHandler.js
  frontend/src/components/modules/policy/policySearchMatrixHandler.js
  frontend/src/utils/gamechangerUtils.js
Labels: bugfix, v1.14

#505 Fixing related searches showing all searches in edge case
  backend/node_app/utils/MLsearchUtility.js
Labels: bugfix, v1.14

#510 updating get all orgs logic
  backend/node_app/modules/policy/policySearchHandler.js
  backend/node_app/utils/searchUtility.js
Labels: bugfix, v1.14

#509 bigfix/sprint-116
  backend/node_app/controllers/appStatsController.js
  backend/node_app/modules/policy/policySearchHandler.js
  backend/node_app/utils/MLsearchUtility.js
  backend/node_app/utils/routeUtility.js
  backend/node_app/utils/searchUtility.js
  backend/test/resources/mockResponses/qaESReturn.js
  backend/test/utils/searchUtility.test.js
  frontend/package.json
  frontend/src/components/analystTools/GCDocumentsComparisonTool.js
  frontend/src/components/modules/policy/policySearchHandler.js
  frontend/src/components/modules/policy/policySearchMatrixHandler.js
  frontend/src/utils/gamechangerUtils.js
Labels: bugfix, v1.14

#520 Hotfix/eda dct
  backend/node_app/controllers/analystToolsController.js
  backend/node_app/modules/eda/edaExportHandler.js
  backend/node_app/modules/eda/edaSearchUtility.js
  backend/test/modules/eda/edaExportHandler.test.js
  backend/test/modules/eda/edaSearchUtility.test.js
  backend/test/utils/searchUtility.test.js
  frontend/package-lock.json
  frontend/src/components/analystTools/GCDocumentsComparisonTool.js
  frontend/src/components/analystTools/index.js
  frontend/src/components/api/gameChanger-service-api.js
  frontend/src/components/factories/analystToolsFactory.js
  frontend/src/components/modules/eda/edaAnalyticsToolsHandler.js
  frontend/src/components/modules/eda/edaContext.js
  frontend/src/components/modules/eda/edaDocumentExplorer.js
  frontend/src/components/modules/eda/edaDocumentsComparisonTool.js
  frontend/src/components/modules/eda/edaMainViewHandler.js
  frontend/src/components/modules/eda/edaNavigationHandler.js
  frontend/src/components/modules/policy/policyContext.js
  frontend/src/components/modules/policy/policyDocumentsComparisonTool.js
  frontend/src/components/modules/policy/policyMainViewHandler.js
Labels: bugfix, v1.14

#521 Task/eda show metadata
  backend/node_app/modules/eda/edaSearchUtility.js
  backend/test/modules/eda/edaSearchUtility.test.js
  frontend/src/components/common/GCAccordion.js
  frontend/src/components/modules/eda/edaCardHandler.js
  frontend/src/components/modules/eda/edaSearchHandler.js
  frontend/src/components/modules/eda/edaSearchMatrixHandler.js
  frontend/src/components/modules/eda/edaUtils.js
  frontend/src/containers/JBookProfilePage.js
Labels: feature, v1.14

#519 Bugfix/sprint 117
  backend/node_app/utils/MLsearchUtility.js
  frontend/src/components/admin/MLDashboard/index.scss
  frontend/src/components/admin/MLDashboard/s3.js
  frontend/src/components/details/documentDetailsPage.js
  frontend/src/components/modules/policy/policyCardHandler.js
Labels: bugfix, v1.14

#523 Feature/eda
  backend/node_app/controllers/analystToolsController.js
  backend/node_app/modules/eda/edaExportHandler.js
  backend/node_app/modules/eda/edaSearchUtility.js
  backend/test/modules/eda/edaExportHandler.test.js
  backend/test/modules/eda/edaSearchUtility.test.js
  backend/test/utils/searchUtility.test.js
  frontend/package-lock.json
  frontend/src/components/analystTools/GCDocumentsComparisonTool.js
  frontend/src/components/analystTools/index.js
  frontend/src/components/api/gameChanger-service-api.js
  frontend/src/components/common/GCAccordion.js
  frontend/src/components/factories/analystToolsFactory.js
  frontend/src/components/modules/eda/edaAnalyticsToolsHandler.js
  frontend/src/components/modules/eda/edaCardHandler.js
  frontend/src/components/modules/eda/edaContext.js
  frontend/src/components/modules/eda/edaDocumentExplorer.js
  frontend/src/components/modules/eda/edaDocumentsComparisonTool.js
  frontend/src/components/modules/eda/edaMainViewHandler.js
  frontend/src/components/modules/eda/edaNavigationHandler.js
  frontend/src/components/modules/eda/edaSearchHandler.js
  frontend/src/components/modules/eda/edaSearchMatrixHandler.js
  frontend/src/components/modules/eda/edaUtils.js
  frontend/src/components/modules/policy/policyContext.js
  frontend/src/components/modules/policy/policyDocumentsComparisonTool.js
  frontend/src/components/modules/policy/policyMainViewHandler.js
  frontend/src/containers/JBookProfilePage.js
Labels: bugfix, v1.14

#532 did this work
  frontend/src/components/modules/jbook/InputFilter.js
  frontend/src/components/modules/jbook/jbookSearchHandler.js
  frontend/src/components/modules/jbook/jbookSearchMatrixHandler.js
  frontend/src/components/modules/policy/policyMainViewHandler.js
Labels: bugfix, v1.15

#533 Feature/greg l value chain
  backend/index.js
  backend/node_app/config/constants.js
  backend/node_app/controllers/cacheController.js
  backend/node_app/lib/cronJobs.js
  backend/node_app/modules/globalSearch/globalSearchHandler.js
  backend/node_app/modules/globalSearch/globalSearchUtils.js
  backend/test/modules/globalSearch/globalSearchHandler.test.js
  frontend/package.json
  frontend/src/components/modules/globalSearch/globalSearchHandler.js
  frontend/src/components/modules/globalSearch/globalSearchMainViewHandler.js
Labels: feature, v1.15

#539 Feature/greg l value chain
  Dockerfile.prod
  backend/index.js
  backend/node_app/modules/globalSearch/globalSearchHandler.js
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/src/components/modules/globalSearch/globalSearchHandler.js
  frontend/src/components/modules/globalSearch/globalSearchMainViewHandler.js
Labels: feature, v1.15

#525 Feature/swap
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/admin/MLDashboard/s3.js
  frontend/src/components/admin/SearchPdfMapping.js
  frontend/src/components/graph/GraphNodeCluster2D.js
  frontend/src/components/modules/eda/edaSummaryView.js
  frontend/src/components/modules/policy/policyAnalyticsToolsHandler.js
  frontend/src/components/modules/policy/policySearchMatrixHandler.js
Labels: feature, v1.15

#522 UOT-140332 - remove top description of user profile
  frontend/src/components/user/UserProfile.js
Labels: bugfix, v1.15

#537 fix case if pdf is capitalized in file extension
  frontend/src/components/documentViewer/PDFViewer.js
Labels: bugfix, v1.15

#529 Task/uot 142922
  frontend/src/components/dataTracker/GCDataStatusTracker.js
  frontend/src/styles.css
Labels: feature, v1.15

#545 UOT-143953
  frontend/src/components/admin/MLDashboard/s3.js
Labels: feature, v1.15

#547 Bugfix/jbook-portfolio Minor fixes to jbook portfolio builder
  frontend/src/components/common/GCAccordion.js
  frontend/src/components/modules/jbook/jbookPortfolioBuilder.js
Labels: bugfix, v1.15

#536 Feature/uot 141982 document compare endpoint
  backend/node_app/controllers/analystToolsController.js
  backend/node_app/lib/mlApiClient.js
  backend/node_app/utils/searchUtility.js
  backend/test/controllers/analystToolsController.test.js
  frontend/src/components/admin/MLDashboard/models.js
  frontend/src/components/analystTools/GCDocumentsComparisonTool.js
  frontend/src/containers/GamechangerAdminPage.js
Labels: feature, v1.15

#550 Fix/update es jbook filters
  backend/node_app/modules/jbook/jbookSearchHandler.js
  backend/node_app/modules/jbook/jbookSearchUtility.js
  backend/node_app/utils/searchUtility.js
  backend/test/modules/jbook/jbookSearchHandler.test.js
Labels: bugfix, v1.15

#552 Task/jbook qlik link
  frontend/package-lock.json
  frontend/src/components/modules/jbook/jbookMainViewHandler.js
Labels: feature, v1.15

#554 remove xlsx import
  frontend/src/components/admin/SearchPdfMapping.js
Labels: bugfix, v1.15

#543 Feature/user data 1
  backend/node_app/controllers/appStatsController.js
  backend/node_app/routes/gameChangerRouter.js
  backend/node_app/utils/sendFileUtility.js
  frontend/package.json
  frontend/src/components/admin/MLDashboard/s3.js
  frontend/src/components/admin/SearchPdfMapping.js
  frontend/src/components/api/gameChanger-service-api.js
  frontend/src/components/telemetry/Matomo.js
Labels: feature, v1.15

#541 Bugfix/sprint 117
  frontend/src/components/admin/APIRequests.js
  frontend/src/components/admin/AdminList/index.js
  frontend/src/components/admin/CloneList/index.js
  frontend/src/components/admin/HomepageEditor/index.js
  frontend/src/components/admin/MLDashboard/info.js
  frontend/src/components/admin/ReviewerList/index.js
  frontend/src/components/admin/SearchPdfMapping.js
  frontend/src/components/admin/UserList/index.js
  frontend/src/components/cards/GCFavoriteCard.js
  frontend/src/components/common/GCAccordion.js
  frontend/src/components/common/GCCloseButton.js
  frontend/src/components/documentViewer/PDFViewer.js
  frontend/src/components/modules/cdo/cdoSearchHandler.js
  frontend/src/components/modules/eda/edaSearchHandler.js
  frontend/src/components/modules/eda/edaSummaryView.js
  frontend/src/components/modules/globalSearch/globalSearchHandler.js
  frontend/src/components/modules/hermes/hermesSearchHandler.js
  frontend/src/components/modules/jbook/userProfile/jbookUserDashboard.js
  frontend/src/components/modules/policy/policyMainViewHandler.js
  frontend/src/components/modules/policy/policySearchHandler.js
  frontend/src/components/modules/simple/simpleSearchHandler.js
  frontend/src/components/searchMetrics/GCSideBar.js
  frontend/src/components/user/AddToGroupModal.js
  frontend/src/components/user/GCUserDashboard.js
  frontend/src/components/user/GroupsPanel.js
  frontend/src/components/user/UserProfile.js
  frontend/src/containers/GameChangerPage.js
Labels: bugfix, v1.15

#542 Feature/dst v117
  frontend/src/components/dataTracker/GCDataStatusTracker.js
  frontend/src/styles.css
Labels: feature, v1.15

#538 Feature/jbook portfolio
  backend/node_app/migrations/jbook/20220412225031-v115-add-portfolio-col.js
  backend/node_app/models/jbook/portfolio.js
  backend/node_app/modules/jbook/jbookDataHandler.js
  backend/node_app/modules/jbook/jbookSearchHandler.js
  backend/node_app/modules/jbook/jbookSearchUtility.js
  backend/node_app/sql/v115.0_update_portfolios.sql
  backend/node_app/utils/searchUtility.js
  backend/test/modules/jbook/jbookDataHandler.test.js
  backend/test/modules/jbook/jbookSearchHandler.test.js
  backend/test/resources/mockResponses/jbookMockData.js
  frontend/src/components/common/GCAccordion.js
  frontend/src/components/modules/jbook/jbookAddTagsModal.js
  frontend/src/components/modules/jbook/jbookAddUsersModal.js
  frontend/src/components/modules/jbook/jbookAdminMainViewHandler.js
  frontend/src/components/modules/jbook/jbookMainViewHandler.js
  frontend/src/components/modules/jbook/jbookPortfolioBuilder.js
  frontend/src/components/modules/jbook/jbookPortfolioModal.js
Labels: feature, v1.15

#555 Pull ES filter data from ES for Jbook
  backend/node_app/modules/jbook/jbookSearchHandler.js
  backend/node_app/modules/jbook/jbookSearchUtility.js
  backend/node_app/utils/searchUtility.js
  backend/test/modules/jbook/jbookSearchHandler.test.js
  frontend/src/components/modules/jbook/jbookMainViewHelper.js
  frontend/src/components/modules/jbook/jbookSearchMatrixHandler.js
Labels: feature, v1.16

#570 bugfix/UOT-146338 - Org Details Page
  backend/node_app/modules/policy/policyGraphHandler.js
Labels: bugfix, v1.16

#562 UOT-144552
  backend/node_app/controllers/feedbackController.js
  frontend/src/components/admin/SearchPdfMapping.js
Labels: feature, v1.16

#560 Bugfix/uot-143789 - pre search filter bug
  frontend/src/components/modules/policy/policySearchHandler.js
Labels: bugfix, v1.16

#569 Feature/jbook merging
  backend/node_app/modules/jbook/jbookDataHandler.js
  backend/node_app/modules/jbook/jbookSearchHandler.js
  backend/node_app/modules/jbook/jbookSearchUtility.js
  backend/node_app/utils/searchUtility.js
  backend/test/modules/jbook/jbookDataHandler.test.js
  backend/test/modules/jbook/jbookSearchHandler.test.js
  frontend/src/components/common/GCAccordion.js
  frontend/src/components/modules/jbook/jbookContext.js
  frontend/src/components/modules/jbook/jbookJAICHelper.js
  frontend/src/components/modules/jbook/jbookMainViewHandler.js
  frontend/src/components/modules/jbook/jbookMainViewHelper.js
  frontend/src/components/modules/jbook/jbookPOCHelper.js
  frontend/src/components/modules/jbook/jbookPOCReviewForm.js
  frontend/src/components/modules/jbook/jbookSearchHandler.js
  frontend/src/components/modules/jbook/jbookSearchMatrixHandler.js
  frontend/src/components/modules/jbook/jbookServiceHelper.js
  frontend/src/components/modules/jbook/profilePage/jbookProfilePageHelper.js
  frontend/src/components/modules/jbook/profilePage/profilePageStyles.js
  frontend/src/containers/JBookProfilePage.js
Labels: feature, v1.16

#573 updated look for qlik link
  frontend/src/components/modules/jbook/jbookMainViewHandler.js
  frontend/src/utils/gamechangerUtils.js
Labels: bugfix, v1.15.1

#575 Advana release/v1.15.1
  backend/node_app/models/jbook/feedback.js
  backend/node_app/modules/jbook/jbookDataHandler.js
  backend/node_app/modules/jbook/jbookSearchHandler.js
  backend/node_app/modules/jbook/jbookSearchUtility.js
  backend/node_app/utils/searchUtility.js
  backend/test/modules/jbook/jbookDataHandler.test.js
  backend/test/modules/jbook/jbookSearchHandler.test.js
  frontend/src/components/common/GCAccordion.js
  frontend/src/components/modules/jbook/jbookContext.js
  frontend/src/components/modules/jbook/jbookJAICHelper.js
  frontend/src/components/modules/jbook/jbookMainViewHandler.js
  frontend/src/components/modules/jbook/jbookMainViewHelper.js
  frontend/src/components/modules/jbook/jbookPOCHelper.js
  frontend/src/components/modules/jbook/jbookPOCReviewForm.js
  frontend/src/components/modules/jbook/jbookSearchHandler.js
  frontend/src/components/modules/jbook/jbookSearchMatrixHandler.js
  frontend/src/components/modules/jbook/jbookServiceHelper.js
  frontend/src/components/modules/jbook/profilePage/jbookProfilePageHelper.js
  frontend/src/components/modules/jbook/profilePage/profilePageStyles.js
  frontend/src/containers/JBookProfilePage.js
  frontend/src/utils/gamechangerUtils.js
Labels: release, v1.15.1

#559 [UOT-145550] Updates to Organization Details page to incorporate `Org Head` and `Org Type(s)` information in table
  backend/node_app/modules/policy/policyGraphHandler.js
  frontend/src/containers/GameChangerDetailsPage.js
Labels: feature, v1.16

#578 Bugfix/pagehit no mapping
  backend/node_app/modules/jbook/jbookDataMapping.js
  backend/node_app/modules/jbook/jbookSearchUtility.js
Labels: bugfix, v1.16

#579 Update jbook card front
  frontend/src/components/modules/jbook/jbookCardHandler.js
  frontend/src/utils/jbookUtilities.js
Labels: bugfix, v1.16

#577 adds sort by relevance as default
  backend/node_app/modules/jbook/jbookSearchUtility.js
  frontend/src/components/modules/jbook/jbookContext.js
  frontend/src/components/modules/jbook/jbookSearchHandler.js
Labels: bugfix, v1.16

#576 Task/UOT-146324
  backend/node_app/controllers/appStatsController.js
  backend/test/controllers/appStatsController.test.js
  frontend/src/components/admin/SearchPdfMapping.js
Labels: feature, v1.16

#564 Task/mainpage portfolio
  backend/node_app/migrations/game_changer/20220510223219-v117-update-clone-meta-add-header.js
  backend/node_app/migrations/jbook/20220519234618-v117-update-review-table.js
  backend/node_app/models/game_changer/gc_meta.js
  backend/node_app/models/jbook/review.js
  backend/node_app/modules/eda/edaSearchHandler.js
  backend/node_app/modules/jbook/jbookDataHandler.js
  backend/node_app/modules/jbook/jbookDataMapping.js
  backend/node_app/modules/jbook/jbookSearchHandler.js
  backend/node_app/modules/jbook/jbookSearchUtility.js
  backend/node_app/sql/v117_update_clone_meta.sql
  backend/test/modules/eda/edaSearchHandler.test.js
  backend/test/modules/jbook/jbookDataHandler.test.js
  backend/test/resources/mockResponses/jbookMockData.js
  frontend/package-lock.json
  frontend/src/components/mainView/ViewHeader.js
  frontend/src/components/modules/default/defaultViewHeaderHandler.js
  frontend/src/components/modules/eda/edaViewHeaderHandler.js
  frontend/src/components/modules/jbook/jbookAdminMainViewHandler.js
  frontend/src/components/modules/jbook/jbookCardHandler.js
  frontend/src/components/modules/jbook/jbookContext.js
  frontend/src/components/modules/jbook/jbookJAICHelper.js
  frontend/src/components/modules/jbook/jbookMainViewHandler.js
  frontend/src/components/modules/jbook/jbookSearchHandler.js
  frontend/src/components/modules/jbook/jbookSearchMatrixHandler.js
  frontend/src/components/modules/jbook/jbookViewHeaderHandler.js
  frontend/src/components/modules/jbook/portfolioBuilder/jbookAddTagsModal.js
  frontend/src/components/modules/jbook/portfolioBuilder/jbookAddUsersModal.js
  frontend/src/components/modules/jbook/portfolioBuilder/jbookPortfolioBuilder.js
  frontend/src/components/modules/jbook/portfolioBuilder/jbookPortfolioModal.js
  frontend/src/components/modules/jbook/portfolioBuilder/jbookPortfolioSelector.js
  frontend/src/components/modules/jbook/profilePage/jbookProfilePageHelper.js
  frontend/src/components/modules/jbook/profilePage/profilePageStyles.js
  frontend/src/components/modules/policy/policyViewHeaderHandler.js
  frontend/src/containers/JBookProfilePage.js
  frontend/src/utils/jbookUtilities.js
Labels: feature, v1.16

#582 Task/uot 140360 - link to FAQ inside the footer
  frontend/src/App.js
  frontend/src/components/aboutUs/GCAboutUs.js
  frontend/src/components/modules/policy/policyMainViewHandler.js
  frontend/src/components/navigation/GCFooter.js
  frontend/src/containers/GameChangerDetailsPage.js
  frontend/src/containers/GameChangerPage.js
  frontend/src/containers/GamechangerAdminPage.js
  frontend/src/containers/GamechangerEsPage.js
  frontend/src/containers/JBookProfilePage.js
  frontend/src/containers/gamechanger.css
  frontend/src/utils/gamechangerUtils.js
  frontend/src/utils/sharedFunctions.js
Labels: feature, v1.16

#583 Uot 146956
  frontend/src/components/modules/jbook/InputFilter.js
  frontend/src/components/modules/jbook/jbookContext.js
  frontend/src/components/modules/jbook/jbookSearchHandler.js
  frontend/src/components/modules/jbook/jbookSearchMatrixHandler.js
Labels: bugfix, v1.16

#586 open jbook items from list view
  frontend/src/components/modules/jbook/jbookCardHandler.js
Labels: bugfix, v1.16

#585 Feature/general
  frontend/src/App.js
  frontend/src/components/aboutUs/GCAboutUs.js
  frontend/src/components/modules/policy/policyMainViewHandler.js
  frontend/src/components/navigation/GCFooter.js
  frontend/src/containers/GameChangerDetailsPage.js
  frontend/src/containers/GameChangerPage.js
  frontend/src/containers/GamechangerAdminPage.js
  frontend/src/containers/GamechangerEsPage.js
  frontend/src/containers/JBookProfilePage.js
  frontend/src/containers/gamechanger.css
  frontend/src/utils/gamechangerUtils.js
  frontend/src/utils/sharedFunctions.js
Labels: feature, v1.16

#568 Feature/jbook portfolio
  backend/node_app/migrations/game_changer/20220510223219-v117-update-clone-meta-add-header.js
  backend/node_app/migrations/jbook/20220519234618-v117-update-review-table.js
  backend/node_app/models/game_changer/gc_meta.js
  backend/node_app/models/jbook/review.js
  backend/node_app/modules/eda/edaSearchHandler.js
  backend/node_app/modules/jbook/jbookDataHandler.js
  backend/node_app/modules/jbook/jbookDataMapping.js
  backend/node_app/modules/jbook/jbookSearchHandler.js
  backend/node_app/modules/jbook/jbookSearchUtility.js
  backend/node_app/sql/v117_update_clone_meta.sql
  backend/test/modules/eda/edaSearchHandler.test.js
  backend/test/modules/jbook/jbookDataHandler.test.js
  backend/test/resources/mockResponses/jbookMockData.js
  frontend/package-lock.json
  frontend/src/components/mainView/ViewHeader.js
  frontend/src/components/modules/default/defaultViewHeaderHandler.js
  frontend/src/components/modules/eda/edaViewHeaderHandler.js
  frontend/src/components/modules/jbook/jbookAdminMainViewHandler.js
  frontend/src/components/modules/jbook/jbookCardHandler.js
  frontend/src/components/modules/jbook/jbookContext.js
  frontend/src/components/modules/jbook/jbookJAICHelper.js
  frontend/src/components/modules/jbook/jbookMainViewHandler.js
  frontend/src/components/modules/jbook/jbookSearchHandler.js
  frontend/src/components/modules/jbook/jbookSearchMatrixHandler.js
  frontend/src/components/modules/jbook/jbookViewHeaderHandler.js
  frontend/src/components/modules/jbook/portfolioBuilder/jbookAddTagsModal.js
  frontend/src/components/modules/jbook/portfolioBuilder/jbookAddUsersModal.js
  frontend/src/components/modules/jbook/portfolioBuilder/jbookPortfolioBuilder.js
  frontend/src/components/modules/jbook/portfolioBuilder/jbookPortfolioModal.js
  frontend/src/components/modules/jbook/portfolioBuilder/jbookPortfolioSelector.js
  frontend/src/components/modules/jbook/profilePage/jbookProfilePageHelper.js
  frontend/src/components/modules/jbook/profilePage/profilePageStyles.js
  frontend/src/components/modules/policy/policyViewHeaderHandler.js
  frontend/src/containers/JBookProfilePage.js
  frontend/src/utils/jbookUtilities.js
Labels: feature, v1.16

#587 Task/jbook simple workflow
  backend/node_app/modules/jbook/jbookDataHandler.js
  frontend/src/components/modules/jbook/jbookJAICHelper.js
  frontend/src/components/modules/jbook/jbookSimpleReviewForm.js
  frontend/src/containers/JBookProfilePage.js
Labels: feature, v1.16

#567 Feature/jbook classification scorecard
  backend/node_app/models/jbook/jbook_classification.js
  backend/node_app/modules/jbook/jbookDataHandler.js
  backend/test/modules/jbook/jbookDataHandler.test.js
  frontend/src/components/modules/jbook/profilePage/jbookProfilePageHelper.js
  frontend/src/containers/JBookProfilePage.js
Labels: feature, v1.16

#588 Feature/jbook simple workflow
  backend/node_app/modules/jbook/jbookDataHandler.js
  frontend/src/components/modules/jbook/jbookJAICHelper.js
  frontend/src/components/modules/jbook/jbookSimpleReviewForm.js
  frontend/src/containers/JBookProfilePage.js
Labels: feature, v1.16

#572 Feature/user data 2
  backend/node_app/controllers/appStatsController.js
  backend/node_app/controllers/feedbackController.js
  backend/test/controllers/appStatsController.test.js
  frontend/src/components/admin/SearchPdfMapping.js
Labels: feature, v1.16

#581 Feature/details page
  backend/node_app/modules/policy/policyGraphHandler.js
  frontend/src/containers/GameChangerDetailsPage.js
Labels: feature, v1.16

#589 Feature/jbook merging
  backend/node_app/lib/ESSearchLib.js
  backend/node_app/lib/dataLibrary.js
  backend/node_app/modules/jbook/jbookDataHandler.js
  backend/node_app/modules/jbook/jbookDataMapping.js
  backend/node_app/modules/jbook/jbookSearchHandler.js
  backend/node_app/modules/jbook/jbookSearchUtility.js
  backend/node_app/modules/policy/policyGraphHandler.js
  backend/test/modules/jbook/jbookDataHandler.test.js
  backend/test/modules/jbook/jbookSearchHandler.test.js
  backend/test/resources/mockResponses/jbookMockData.js
  frontend/src/components/admin/MLDashboard/s3.js
  frontend/src/components/modules/jbook/InputFilter.js
  frontend/src/components/modules/jbook/jbookCardHandler.js
  frontend/src/components/modules/jbook/jbookContext.js
  frontend/src/components/modules/jbook/jbookSearchHandler.js
  frontend/src/components/modules/jbook/jbookSearchMatrixHandler.js
  frontend/src/components/modules/jbook/jbookSimpleReviewForm.js
  frontend/src/components/modules/jbook/profilePage/jbookProfilePageHelper.js
  frontend/src/components/modules/policy/policySearchHandler.js
  frontend/src/containers/JBookProfilePage.js
  frontend/src/utils/jbookUtilities.js
Labels: feature, v1.16

#571 Bugfix/sprint 118
  backend/node_app/modules/jbook/jbookDataMapping.js
  backend/node_app/modules/jbook/jbookSearchUtility.js
  backend/node_app/modules/policy/policyGraphHandler.js
  frontend/src/components/modules/jbook/InputFilter.js
  frontend/src/components/modules/jbook/jbookCardHandler.js
  frontend/src/components/modules/jbook/jbookContext.js
  frontend/src/components/modules/jbook/jbookSearchHandler.js
  frontend/src/components/modules/jbook/jbookSearchMatrixHandler.js
  frontend/src/components/modules/policy/policySearchHandler.js
  frontend/src/utils/jbookUtilities.js
Labels: bugfix, v1.16

#590 Bugfix/118 hotfix - add in import missing from jbookProfilePageHelper
  frontend/src/components/modules/jbook/profilePage/jbookProfilePageHelper.js
Labels: bugfix, v1.16
