Repository dod-advana/gamechanger-web, pull requests merged in 2022-03, with the labels that each got.

#373 feature/UOT-128309
  frontend/src/components/admin/SearchPdfMapping.js
  frontend/src/components/cards/GCCard.js
  frontend/src/components/export/ExportResultsDialog.js
  frontend/src/components/navigation/DecoupledFooter.js
  frontend/src/components/telemetry/Matomo.js
Labels: v1.11

#368 Task/update packages
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/styles.css
Labels: v1.11

#376 Task/uot 131487
  backend/node_app/utils/searchUtility.js
  backend/test/modules/policy/policyGraphHandler.test.js
  backend/test/utils/searchUtility.test.js
  frontend/src/components/modules/default/qaResults.js
Labels: v1.11

#375 Task/dct docview
  backend/node_app/controllers/analystToolsController.js
  backend/node_app/controllers/responsibilityController.js
  backend/node_app/migrations/game_changer/2022021815313775-v111-update-compare-feedback-with-userid.js
  backend/node_app/models/game_changer/compare_feedback.js
  frontend/public/pdfjs/build/pdf.worker.js
  frontend/src/components/analystTools/GCAnalystToolsSideBar.js
  frontend/src/components/analystTools/GCDocumentsComparisonTool.js
  frontend/src/components/analystTools/index.js
  frontend/src/components/cards/GCCard.js
  frontend/src/components/modules/policy/policyAnalyticsToolsHandler.js
  frontend/src/components/modules/policy/policyCardHandler.js
  frontend/src/components/searchMetrics/sidebar.css
  frontend/src/containers/gamechanger.css
  frontend/src/utils/sharedFunctions.js
Labels: v1.11

#374 UOT-128830 - UX Fixes for Covid-19 Clone
  frontend/src/components/modules/cdo/cdoSearchHandler.js
  frontend/src/components/modules/default/defaultCardHandler.js
  frontend/src/components/modules/default/defaultContext.js
  frontend/src/components/modules/default/defaultNavigationHandler.js
  frontend/src/components/modules/default/defaultTitleBarHandler.js
  frontend/src/components/modules/hermes/hermesSearchHandler.js
  frontend/src/components/modules/simple/simpleSearchHandler.js
  frontend/src/images/logos/Covid19-Sidemenu.png
Labels: v1.11

#377 Feature/Uot-134741
  backend/node_app/controllers/appStatsController.js
  frontend/src/components/admin/SearchPdfMapping.js
  frontend/src/components/cards/GCCard.js
Labels: v1.11

#383 Task/UOT-132472 - Graph Re-center Behavior
  frontend/src/components/admin/MLDashboard/models.js
  frontend/src/components/graph/GraphNodeCluster2D.js
  frontend/src/components/graph/policyGraphView.js
Labels: v1.11

#385 Task/UOT-126354 - adding neo4j queries to recommendations
  backend/node_app/utils/searchUtility.js
  backend/test/resources/mockResponses/graphRecSearches.json
  backend/test/utils/searchUtility.test.js
Labels: v1.11

#390 Advana release/v1.10
  Dockerfile.prod
  backend/index.js
  backend/node_app/controllers/analystToolsController.js
  backend/node_app/controllers/appStatsController.js
  backend/node_app/controllers/responsibilityController.js
  backend/node_app/migrations/game_changer/2022021815313775-v111-update-compare-feedback-with-userid.js
  backend/node_app/models/game_changer/compare_feedback.js
  backend/node_app/utils/searchUtility.js
  backend/package-lock.json
  backend/package.json
  backend/test/modules/policy/policyGraphHandler.test.js
  backend/test/resources/mockResponses/graphRecSearches.json
  backend/test/utils/searchUtility.test.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/pdfjs/build/pdf.worker.js
  frontend/src/App.js
  frontend/src/components/admin/MLDashboard/models.js
  frontend/src/components/admin/SearchPdfMapping.js
  frontend/src/components/analystTools/GCAnalystToolsSideBar.js
  frontend/src/components/analystTools/GCDocumentsComparisonTool.js
  frontend/src/components/analystTools/index.js
  frontend/src/components/cards/GCCard.js
  frontend/src/components/export/ExportResultsDialog.js
  frontend/src/components/graph/GraphNodeCluster2D.js
  frontend/src/components/graph/policyGraphView.js
  frontend/src/components/modules/cdo/cdoSearchHandler.js
  frontend/src/components/modules/default/defaultCardHandler.js
  frontend/src/components/modules/default/defaultContext.js
  frontend/src/components/modules/default/defaultNavigationHandler.js
  frontend/src/components/modules/default/defaultTitleBarHandler.js
  frontend/src/components/modules/default/qaResults.js
  frontend/src/components/modules/hermes/hermesSearchHandler.js
  frontend/src/components/modules/policy/policyAnalyticsToolsHandler.js
  frontend/src/components/modules/policy/policyCardHandler.js
  frontend/src/components/modules/simple/simpleSearchHandler.js
  frontend/src/components/navigation/DecoupledFooter.js
  frontend/src/components/searchMetrics/sidebar.css
  frontend/src/components/telemetry/Matomo.js
  frontend/src/containers/gamechanger.css
  frontend/src/images/logos/Covid19-Sidemenu.png
  frontend/src/styles.css
  frontend/src/utils/axiosUtils.js
  frontend/src/utils/sharedFunctions.js
Labels: v1.10

#388 Task/uot 130404
  frontend/src/components/common/TabStyles.js
  frontend/src/components/dataTracker/GCDataStatusTracker.js
Labels: v1.11

#382 added endpoint for getting doc ingest stats
  backend/node_app/controllers/dataTrackerController.js
  backend/node_app/routes/gameChangerRouter.js
  backend/security_scan/route_check/whitelist.list
  backend/test/controllers/dataTrackerController.test.js
  frontend/src/components/api/gameChanger-service-api.js
Labels: v1.11

#391 changed process to use thread id as keys
  backend/node_app/controllers/dataTrackerController.js
  frontend/src/components/admin/MLDashboard/models.js
  frontend/src/components/admin/MLDashboard/s3.js
Labels: v1.11

#395 entity details table now has word wrap
  frontend/src/components/searchMetrics/sidebar.css
  frontend/src/containers/GameChangerDetailsPage.js
Labels: v1.11

#402 fix crash from selecting input paragraph with no results
  frontend/src/components/analystTools/GCDocumentsComparisonTool.js
Labels: v1.11

#398 Task/uot 130405
  backend/node_app/controllers/dataTrackerController.js
  backend/test/controllers/dataTrackerController.test.js
  frontend/src/components/dataTracker/GCDataStatusTracker.js
  frontend/src/components/dataTracker/IngestStats.js
  frontend/src/components/dataTracker/StatPill.js
Labels: v1.11

#410 Task/UOT-136433 - Graph View Performance / Dynamic Node Sizing
  frontend/src/components/graph/GraphNodeCluster2D.js
  frontend/src/components/graph/policyGraphView.js
Labels: v1.11

#412 Task/fix infinite scroll
  frontend/src/components/mainView/MainView.js
Labels: v1.11

#408 Task/uot 131480
  backend/node_app/controllers/adminController.js
  backend/node_app/controllers/userController.js
  backend/node_app/utils/searchUtility.js
  backend/test/controllers/adminController.test.js
  backend/test/utils/searchUtility.test.js
  frontend/src/components/modules/policy/policyMainViewHandler.js
  frontend/src/components/user/GCUserDashboard.js
Labels: v1.11

#403 prevent horizontal scroll bars on policy cards
  frontend/src/components/modules/policy/policyCardHandler.js
Labels: v1.11

#411 Task/add args to mldash
  frontend/src/components/admin/MLDashboard/models.js
Labels: v1.11

#405 Task/more re updates
  frontend/public/pdfjs/web/viewer.js
  frontend/src/components/analystTools/GCResponsibilityDocumentExplorer.js
  frontend/src/components/analystTools/GCResponsibilityExplorer.js
  frontend/src/components/api/gameChanger-service-api.js
  frontend/src/components/common/GCAccordion.js
  frontend/src/components/common/GCAlert.js
  frontend/src/components/modules/policy/policyMainViewHandler.js
  frontend/src/containers/gamechanger.css
Labels: v1.11

#413 UOT-134396 Fix topic details page to reflect all neo4j nodes as listed documents
  backend/node_app/modules/policy/policyGraphHandler.js
  backend/node_app/utils/searchUtility.js
  backend/test/modules/policy/policyGraphHandler.test.js
  backend/test/modules/policy/policySearchHandler.test.js
Labels: v1.11

#414 Updated the user profile button to the side bar and also fixed favori…
  backend/node_app/controllers/userController.js
  backend/node_app/modules/globalSearch/globalSearchHandler.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/mainView/MainView.js
  frontend/src/components/modules/budgetSearch/budgetSearchSearchBarHandler.js
  frontend/src/components/modules/default/defaultSearchBarHandler.js
  frontend/src/components/modules/eda/edaNavigationHandler.js
  frontend/src/components/modules/eda/edaSearchBarHandler.js
  frontend/src/components/modules/globalSearch/globalSearchNavigationHandler.js
  frontend/src/components/modules/policy/policyContext.js
  frontend/src/components/modules/policy/policyMainViewHandler.js
  frontend/src/components/modules/policy/policyNavigationHandler.js
  frontend/src/components/modules/policy/policySearchBarHandler.js
  frontend/src/components/user/GCUserDashboard.js
  frontend/src/utils/sharedFunctions.js
Labels: v1.11

#420 feature/UOT-136025
  backend/node_app/controllers/appStatsController.js
  backend/node_app/controllers/userController.js
  backend/test/controllers/appStatsController.test.js
  backend/test/controllers/userController.test.js
  frontend/src/components/telemetry/Matomo.js
  frontend/src/components/telemetry/TrackerWrapperHooks.js
  frontend/src/config/config.js
Labels: v1.12

#423 Task/uot 134390
  backend/node_app/controllers/feedbackController.js
  backend/node_app/migrations/game_changer/2022032214385620-v113-create-doc-ingest-request.js.js
  backend/node_app/models/game_changer/doc_ingest_requests.js
  backend/node_app/routes/gameChangerRouter.js
  backend/security_scan/route_check/whitelist.list
  backend/test/controllers/feedbackController.test.js
  frontend/src/components/api/gameChanger-service-api.js
  frontend/src/components/common/SimpleTable.js
  frontend/src/components/details/documentDetailsPage.js
  frontend/src/components/modules/policy/policyCardHandler.js
  frontend/src/containers/GameChangerDetailsPage.js
Labels: v1.12

#426 Bug/ getUserData not returning
  backend/node_app/controllers/userController.js
  backend/test/controllers/userController.test.js
Labels: v1.12

#424 UOT-137807 - change organization filter to source filter
  frontend/src/components/modules/policy/policyMainViewHandler.js
  frontend/src/components/user/GCUserDashboard.js
Labels: v1.12

#427 fixed the tutorial, clears filters before starting
  backend/index.js
  frontend/src/components/modules/policy/policyNavigationHandler.js
  frontend/src/components/tutorial/Tutorial.js
  frontend/src/containers/GameChangerPage.js
Labels: v1.12

#432 add fpds fields, fix filters showing without search, add results count
  backend/node_app/modules/eda/edaExportHandler.js
  backend/node_app/modules/eda/edaSearchHandler.js
  backend/node_app/modules/eda/edaSearchUtility.js
  backend/test/modules/eda/edaSearchHandler.test.js
  backend/test/modules/eda/edaSearchUtility.test.js
  frontend/src/App.js
  frontend/src/components/mainView/ViewHeader.js
  frontend/src/components/modules/eda/edaCardHandler.js
  frontend/src/components/modules/eda/edaContractDetailsPage.js
  frontend/src/components/modules/eda/edaMainViewHandler.js
  frontend/src/components/modules/eda/edaSearchMatrixHandler.js
  frontend/src/components/modules/eda/edaUtils.js
  frontend/src/containers/GameChangerDetailsPage.js
Labels: v1.12

#428 handling 'S' case of plural forms
  frontend/src/components/modules/jbook/jbookSearchMatrixHandler.js
Labels: v1.12

#429 Task/uot 138089
  frontend/src/components/analystTools/GCAnalystToolsSideBar.js
  frontend/src/components/analystTools/GCDocumentsComparisonTool.js
  frontend/src/components/modules/policy/policyAnalyticsToolsHandler.js
  frontend/src/components/modules/policy/policyContext.js
Labels: v1.12

#430 fix overlapping reference sections
  frontend/src/components/documentViewer/DocumentExplorer.js
  frontend/src/components/modules/default/defaultDocumentExplorer.js
  frontend/src/components/modules/eda/edaDocumentExplorer.js
  frontend/src/components/modules/policy/policyCardHandler.js
Labels: v1.12

#431 fix checkmark issue on RE chart view
  frontend/src/components/analystTools/GCResponsibilityTracker.js
Labels: v1.12

#433 hotfix/getUserLastOpened
  backend/node_app/controllers/appStatsController.js
  backend/node_app/controllers/userController.js
  frontend/src/components/modules/policy/policyCardHandler.js
  frontend/src/components/telemetry/Matomo.js
Labels: v1.12

#434 Bugfix/various bugfixes
  backend/index.js
  backend/node_app/controllers/appSettingsController.js
  backend/node_app/routes/gameChangerRouter.js
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/admin/APIRequests.js
  frontend/src/components/admin/GeneralAdminButtons/index.js
  frontend/src/components/api/RequestAPIKeyDialog.js
  frontend/src/components/api/gameChanger-service-api.js
  frontend/src/components/modules/jbook/jbookNavigationHandler.js
  frontend/src/components/modules/jbook/jbookSearchBarHandler.js
  frontend/src/components/navigation/DecoupledFooter.js
  frontend/src/components/navigation/GCFooter.js
  frontend/src/components/searchBar/GCSearchBanner.js
  frontend/src/components/user/GCUserInfoModal.js
  frontend/src/config/config.js
  frontend/src/containers/GameChangerPage.js
  frontend/src/utils/axiosUtils.js
Labels: v1.12

#436 Task/updating packages for swap
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/admin/ResponsibilityUpdates/index.js
  frontend/src/components/analystTools/GCResponsibilityDocumentExplorer.js
  frontend/src/components/cards/GCCard.js
  frontend/src/components/details/documentDetailsPage.js
  frontend/src/components/modules/default/defaultDocumentExplorer.js
  frontend/src/components/modules/default/defaultMainViewHandler.js
  frontend/src/components/modules/default/qaResults.js
  frontend/src/components/modules/eda/edaMainViewHandler.js
  frontend/src/components/modules/policy/policyMainViewHandler.js
  frontend/src/containers/gamechanger.css
Labels: v1.12

#435 Task/uot 137806
  frontend/src/components/modules/policy/policyNavigationHandler.js
  frontend/src/images/icon/crowdsourcing.png
  frontend/src/images/icon/datatracker.png
  frontend/src/images/icon/helpicon.png
  frontend/src/images/icon/userfeedback.png
Labels: v1.12

#440 Task/UOT-137843 - Graph UI Updates
  frontend/src/components/analystTools/GCDocumentsComparisonTool.js
  frontend/src/components/analystTools/index.js
  frontend/src/components/graph/GraphNodeCluster2D.js
  frontend/src/components/graph/policyGraphView.js
  frontend/src/containers/GameChangerDetailsPage.js
Labels: v1.12

#443 task/UOT-137812 - Fixes for new graph data
  frontend/src/components/common/SimpleTable.js
  frontend/src/components/graph/defaultGraphView.js
  frontend/src/components/graph/policyGraphView.js
  frontend/src/containers/GameChangerDetailsPage.js
Labels: v1.12

#441 fix faqs
  backend/node_app/sql/v114.0_update_faq.sql
  frontend/src/components/aboutUs/GCAboutUs.js
  frontend/src/containers/gamechanger.css
Labels: v1.12

#438 feature/UOT-136032
  backend/node_app/controllers/appStatsController.js
  frontend/src/components/admin/SearchPdfMapping.js
  frontend/src/components/telemetry/Matomo.js
Labels: v1.12

#439 UOT-138216 add portfolio table and jaic portfolio row
  backend/node_app/migrations/jbook/20220328224458-v114-create-portfolio-table.js
  backend/node_app/models/jbook/portfolio.js
  backend/node_app/sql/v114.0_add_jaic_portfolio.sql
Labels: v1.12
