Repository dod-advana/gamechanger-web, pull requests merged in 2022-04, with the labels that each got.

#445 bugfix/UOT-138573 Include full metadata from back of card to document details page
  backend/node_app/migrations/jbook/20220328224458-v114-create-portfolio-table.js
  backend/node_app/models/jbook/portfolio.js
  backend/node_app/utils/searchUtility.js
  backend/test/utils/searchUtility.test.js
  frontend/src/components/details/documentDetailsPage.js
  frontend/src/components/modules/policy/policyCardHandler.js
Labels: v1.12

#446 Ninja fix for underscore package update
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: v1.12

#460 Fixes cors vuln. Add REQUEST_ORIGIN_ALLOWED to env vars with localhos…
  backend/index.js
Labels: v1.12, bugfix

#461 multiple fixes for doc details page
  frontend/src/components/common/SimpleTable.js
  frontend/src/components/details/documentDetailsPage.js
Labels: v1.12, bugfix

#465 new getting started guide
  README.md
Labels: v1.13

#464 Bugfix/UOT-139876
  backend/index.js
  frontend/src/components/modules/default/defaultMainViewHandler.js
Labels: bugfix, v1.13

#453 UOT-138571 Remove Related Searches white space, Fix sort function
  .github/CODEOWNERS
  .gitignore
  backend/node_app/migrations/jbook/20220329194330-114-update-review-table.js
  backend/node_app/models/jbook/review.js
  backend/node_app/modules/jbook/jbookDataMapping.js
  backend/node_app/sql/v114.0_update_review_portfolio.sql
  backend/node_app/utils/searchUtility.js
  frontend/src/components/api/gameChanger-service-api.js
  frontend/src/components/mainView/ViewHeader.js
  frontend/src/components/modules/cdo/cdoCardHandler.js
  frontend/src/components/modules/default/defaultCardHandler.js
  frontend/src/components/modules/eda/edaCardHandler.js
  frontend/src/components/modules/hermes/hermesCardHandler.js
  frontend/src/components/modules/jbook/jbookCardHandler.js
  frontend/src/components/modules/policy/policyCardHandler.js
  frontend/src/components/modules/policy/policySearchHandler.js
  frontend/src/components/searchMetrics/GCSideBar.js
Labels: bugfix, v1.13

#456 UOT-136026
  backend/node_app/controllers/appStatsController.js
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/components/admin/SearchPdfMapping.js
  frontend/src/components/telemetry/Matomo.js
Labels: feature, v1.13

#462 Task/jbook portfolio builder
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE/feature_pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/task_pull_request_template.md
  .gitignore
  backend/node_app/modules/jbook/jbookDataHandler.js
  backend/test/modules/jbook/jbookDataHandler.test.js
  frontend/src/components/modules/jbook/jbookAdminMainViewHandler.js
  frontend/src/components/modules/jbook/jbookPortfolioBuilder.js
Labels: feature, v1.13

#480 swap mui pickers with react-datepickers
  frontend/package.json
  frontend/src/components/admin/SearchPdfMapping.js
  frontend/src/components/modules/eda/edaSummaryView.js
  frontend/src/components/modules/policy/policyAnalyticsToolsHandler.js
  frontend/src/components/modules/policy/policySearchMatrixHandler.js
Labels: feature, v1.13

#482 Task/uot 139857 - adding abbreviation expansions/aliases to related terms
  backend/node_app/modules/policy/policySearchHandler.js
  backend/node_app/utils/searchUtility.js
  backend/test/modules/policy/policySearchHandler.test.js
Labels: feature, v1.13

#469 Bugfix/consent banner and more
  backend/node_app/controllers/externalAPI/externalAPIController.js
  backend/node_app/controllers/userController.js
  backend/node_app/images/email/GAMECHANGER API Newsletter.png
  backend/node_app/images/email/GAMECHANGER User Feedback.png
  backend/node_app/utils/emailUtility.js
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/user/UserFeedback.js
Labels: bugfix, v1.13

#489 Task/uot 142175 - Search Enhancements and Refactoring
  backend/index.js
  backend/node_app/config/constants.js
  backend/node_app/controllers/adminController.js
  backend/node_app/controllers/textSuggestionController.js
  backend/node_app/modules/policy/policyExportHandler.js
  backend/node_app/modules/policy/policyGraphHandler.js
  backend/node_app/modules/policy/policySearchHandler.js
  backend/node_app/utils/MLsearchUtility.js
  backend/node_app/utils/searchUtility.js
  backend/test/controllers/textSuggestionController.test.js
  backend/test/modules/policy/policyGraphHandler.test.js
  backend/test/resources/testUtility.js
  backend/test/utils/MLsearchUtility.test.js
  backend/test/utils/searchUtility.test.js
  frontend/src/components/api/gameChanger-service-api.js
  frontend/src/components/mainView/ViewHeader.js
  frontend/src/components/modules/default/defaultMainViewHandler.js
  frontend/src/components/modules/policy/policySearchHandler.js
  frontend/src/components/searchMetrics/GCSideBar.js
Labels: feature, v1.13

#490 Task/uot 137808
  backend/node_app/controllers/dataTrackerController.js
  backend/test/controllers/dataTrackerController.test.js
  frontend/src/components/dataTracker/GCDataStatusTracker.js
  frontend/src/components/dataTracker/IngestStats.js
  frontend/src/components/modules/default/defaultNavigationHandler.js
  frontend/src/components/modules/policy/policyNavigationHandler.js
  frontend/src/components/searchBar/GCSearchBanner.js
Labels: feature, v1.13

#491 Update and add new eda search filters
  backend/node_app/modules/eda/edaSearchUtility.js
  backend/test/modules/eda/edaSearchUtility.test.js
  frontend/src/components/api/gameChanger-service-api.js
  frontend/src/components/modules/eda/edaContext.js
  frontend/src/components/modules/eda/edaSearchMatrixHandler.js
Labels: feature, v1.13

#487 UOT-141788
  backend/node_app/controllers/transformerController.js
  backend/node_app/lib/mlApiClient.js
  backend/node_app/routes/gameChangerRouter.js
  frontend/src/components/admin/MLDashboard/s3.js
  frontend/src/components/admin/SearchPdfMapping.js
  frontend/src/components/api/gameChanger-service-api.js
Labels: feature, v1.13

#502 fixing test for acronym expansion
  .github/workflows/test_node.js.yml
  backend/test/modules/policy/policySearchHandler.test.js
  backend/test/utils/searchUtility.test.js
Labels: bugfix, v1.13

#493 Feature/search improvements 3
  .github/workflows/test_node.js.yml
  backend/node_app/config/constants.js
  backend/node_app/controllers/adminController.js
  backend/node_app/modules/policy/policyExportHandler.js
  backend/node_app/modules/policy/policyGraphHandler.js
  backend/node_app/modules/policy/policySearchHandler.js
  backend/node_app/utils/MLsearchUtility.js
  backend/node_app/utils/searchUtility.js
  backend/test/modules/policy/policyGraphHandler.test.js
  backend/test/modules/policy/policySearchHandler.test.js
  backend/test/resources/testUtility.js
  backend/test/utils/MLsearchUtility.test.js
  backend/test/utils/searchUtility.test.js
Labels: feature, v1.13

#492 Feature/dst
  backend/node_app/controllers/dataTrackerController.js
  backend/test/controllers/dataTrackerController.test.js
  frontend/src/components/dataTracker/GCDataStatusTracker.js
  frontend/src/components/dataTracker/IngestStats.js
  frontend/src/components/modules/default/defaultNavigationHandler.js
  frontend/src/components/modules/policy/policyNavigationHandler.js
  frontend/src/components/searchBar/GCSearchBanner.js
  frontend/src/styles.css
Labels: feature, v1.13

#470 Feature/user data
  backend/node_app/controllers/appStatsController.js
  backend/node_app/controllers/transformerController.js
  backend/node_app/lib/mlApiClient.js
  backend/node_app/routes/gameChangerRouter.js
  backend/package-lock.json
  backend/test/controllers/appStatsController.test.js
  frontend/package-lock.json
  frontend/src/components/admin/MLDashboard/s3.js
  frontend/src/components/admin/SearchPdfMapping.js
  frontend/src/components/api/gameChanger-service-api.js
  frontend/src/components/documentViewer/PDFViewer.js
  frontend/src/components/telemetry/Matomo.js
  frontend/src/utils/gamechangerUtils.js
Labels: feature, v1.13

#503 Task/global search fixes
  backend/index.js
  backend/node_app/config/constants.js
  backend/node_app/modules/globalSearch/globalSearchHandler.js
  backend/node_app/utils/DataCatalogUtils.js
  backend/node_app/utils/startupUtils.js
  backend/package-lock.json
  backend/package.json
  frontend/src/components/modules/globalSearch/SearchTabBar.js
  frontend/src/components/modules/globalSearch/globalSearchHandler.js
  frontend/src/components/modules/globalSearch/globalSearchMainViewHandler.js
  frontend/src/components/modules/globalSearch/globalSearchTitleBarHandler.js
  frontend/src/components/modules/policy/policyTitleBarHandler.js
  frontend/src/containers/GameChangerPage.js
Labels: feature, v1.13

#504 Feature/global search
  backend/index.js
  backend/node_app/config/constants.js
  backend/node_app/modules/globalSearch/globalSearchHandler.js
  backend/node_app/utils/DataCatalogUtils.js
  backend/node_app/utils/startupUtils.js
  backend/package-lock.json
  backend/package.json
  frontend/src/components/cards/GCCard.js
  frontend/src/components/modules/globalSearch/SearchTabBar.js
  frontend/src/components/modules/globalSearch/globalSearchHandler.js
  frontend/src/components/modules/globalSearch/globalSearchMainViewHandler.js
  frontend/src/components/modules/globalSearch/globalSearchTitleBarHandler.js
  frontend/src/components/modules/policy/policyTitleBarHandler.js
  frontend/src/containers/GameChangerPage.js
Labels: feature, v1.13

#495 Feature/eda
  backend/node_app/modules/eda/edaSearchUtility.js
  backend/test/modules/eda/edaSearchUtility.test.js
  frontend/src/components/modules/eda/edaContext.js
  frontend/src/components/modules/eda/edaSearchMatrixHandler.js
  frontend/src/components/modules/eda/edaTitleBarHandler.js
Labels: feature, v1.13

#449 Task/UOT-137812 - Fixes for new graph data (pt 2)
  backend/node_app/modules/policy/policyGraphHandler.js
  frontend/src/components/common/SimpleTable.js
  frontend/src/components/graph/policyGraphView.js
  frontend/src/components/searchMetrics/GCSideBar.js
  frontend/src/containers/GameChangerDetailsPage.js
Labels: feature
